"use client";
import { useState } from "react";
import type { PortfolioMessage, PortfolioProject } from "@/lib/portfolio";

const empty={id:0,title:"",type:"",tech:[],text:"",href:"",image:"",position:0,published:true} satisfies PortfolioProject;
export function AdminPortfolio({configured,initialProjects,initialResume,initialMessages}:{configured:boolean;initialProjects:PortfolioProject[];initialResume:string;initialMessages:PortfolioMessage[]}){
 const [projects,setProjects]=useState(initialProjects),[messages,setMessages]=useState(initialMessages),[form,setForm]=useState<PortfolioProject>(empty),[resume,setResume]=useState(initialResume),[message,setMessage]=useState("");
 const field=(name:keyof PortfolioProject,value:unknown)=>setForm(current=>({...current,[name]:value}));
 async function upload(file:File,kind="thumbnail"){setMessage("Uploading…");const data=new FormData();data.set("file",file);data.set("kind",kind);const response=await fetch("/api/admin/upload",{method:"POST",body:data});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("Upload complete.");return body.url as string;}
 async function save(e:React.FormEvent){e.preventDefault();setMessage("Saving…");const url=form.id>0?`/api/admin/projects/${form.id}`:"/api/admin/projects";const response=await fetch(url,{method:form.id>0?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();if(!response.ok){setMessage(body.error);return}setProjects(current=>form.id>0?current.map(p=>p.id===body.project.id?body.project:p):[...current,body.project].sort((a,b)=>a.position-b.position));setForm(empty);setMessage("Project saved.");}
 async function remove(project:PortfolioProject){if(!confirm(`Delete ${project.title}?`))return;const response=await fetch(`/api/admin/projects/${project.id}`,{method:"DELETE"});if(response.ok){setProjects(current=>current.filter(p=>p.id!==project.id));setMessage("Project deleted.");}}
 return <main className="admin-page"><div className="admin-head"><div><p>Sandipan Das</p><h1>Portfolio control room</h1><span>Manage projects, thumbnails and your current résumé.</span></div><a href="/" target="_blank">View portfolio ↗</a></div>
 {!configured&&<div className="admin-warning"><b>Database setup required.</b><p>Connect Neon Postgres and set <code>DATABASE_URL</code> (or <code>POSTGRES_URL</code>). The default portfolio remains live, but editing is disabled until connected.</p></div>}
 <section className="admin-resume"><div><h2>Current résumé</h2><a href={resume} target="_blank">Open current PDF ↗</a></div><label className={!configured?"disabled":""}>Replace résumé PDF<input disabled={!configured} type="file" accept="application/pdf" onChange={async e=>{const file=e.target.files?.[0];if(file)try{setResume(await upload(file,"resume"))}catch(error){setMessage((error as Error).message)}}}/></label></section>
 <section className="admin-grid"><form onSubmit={save} className="project-form"><h2>{form.id>0?"Edit project":"Add project"}</h2><label>Title<input value={form.title} onChange={e=>field("title",e.target.value)} required/></label><label>Category<input value={form.type} onChange={e=>field("type",e.target.value)} required/></label><label>Description<textarea value={form.text} onChange={e=>field("text",e.target.value)} required rows={4}/></label><label>Technology tags <small>comma separated</small><input value={form.tech.join(", ")} onChange={e=>field("tech",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))}/></label><label>Project URL<input value={form.href} onChange={e=>field("href",e.target.value)} placeholder="https://…"/></label><label>Thumbnail URL<input value={form.image} onChange={e=>field("image",e.target.value)} required/></label><label className="file-label">Or upload thumbnail<input disabled={!configured} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={async e=>{const file=e.target.files?.[0];if(file)try{field("image",await upload(file))}catch(error){setMessage((error as Error).message)}}}/></label><div className="form-row"><label>Order<input type="number" value={form.position} onChange={e=>field("position",Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={form.published} onChange={e=>field("published",e.target.checked)}/> Published</label></div><div className="form-actions"><button disabled={!configured} type="submit">{form.id>0?"Update project":"Create project"}</button>{form.id>0&&<button type="button" className="secondary" onClick={()=>setForm(empty)}>Cancel</button>}</div>{message&&<p className="admin-message">{message}</p>}</form>
 <div className="admin-projects"><h2>Projects <span>{projects.length}</span></h2>{projects.map(project=><article key={project.id}><img src={project.image} alt=""/><div><span>{project.published?"Published":"Draft"} · #{project.position}</span><h3>{project.title}</h3><p>{project.type} · {project.tech.join(" · ")}</p></div><div><button onClick={()=>setForm(project)}>Edit</button><button className="danger" disabled={project.id<0||!configured} onClick={()=>remove(project)}>Delete</button></div></article>)}</div></section>
 <section className="admin-messages"><h2>Contact messages <span>{messages.length}</span></h2>{messages.length===0?<p>No messages yet.</p>:messages.map(item=><article key={item.id}><div><b>{item.name}</b><a href={`mailto:${item.email}`}>{item.email}</a><small>{new Date(item.receivedAt).toLocaleString()}</small></div><div><strong>{item.subject||"Portfolio enquiry"}</strong><p>{item.message}</p></div><button onClick={async()=>{if(confirm("Delete this message?")){const response=await fetch(`/api/admin/messages/${item.id}`,{method:"DELETE"});if(response.ok)setMessages(current=>current.filter(x=>x.id!==item.id))}}}>Delete</button></article>)}</section>
 </main>;
}
