export type ProjectLike = { title: string; type: string; tech: string[]; text: string; href: string; image: string };

type ProjectInsight = {
  audience: string;
  challenge: string;
  solution: string;
  businessValue: string;
  features: string[];
  benefits: string[];
  tradeoffs: string[];
};

export const projectSlug = (title: string) => title.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

const insights: Record<string, ProjectInsight> = {
  "Aaranya": { audience: "Diners looking for a refined modern Indian restaurant experience.", challenge: "Restaurant websites often list information without conveying atmosphere or making reservation intent easy to act on.", solution: "An editorial, motion-led experience combines menu discovery, brand storytelling and a direct booking journey.", businessValue: "Stronger brand perception and a clearer path from browsing to table enquiries.", features: ["Seasonal menu storytelling", "Responsive reservation journey", "Immersive visual direction", "Mobile-first navigation"], benefits: ["Builds premium brand trust", "Makes menu discovery effortless", "Reduces booking friction"], tradeoffs: ["Rich imagery requires careful optimization", "Motion must respect accessibility preferences"] },
  "Hospital Management System": { audience: "Hospitals, clinicians, reception teams, patients and finance staff.", challenge: "Appointments, clinical records, prescriptions and billing become fragmented when departments use disconnected workflows.", solution: "A role-based platform unifies seven user types around secure operational and patient-care processes.", businessValue: "Improves coordination, record visibility and administrative efficiency while reducing duplicate data entry.", features: ["Seven role-based dashboards", "Appointments and patient records", "Prescriptions and billing", "JWT-secured access"], benefits: ["Centralized operational data", "Clear responsibility by role", "Faster patient-service workflows"], tradeoffs: ["Healthcare data requires strict governance", "Role permissions need continuous review"] },
  "MelBuddy": { audience: "People discovering social activities and organizers managing bookings.", challenge: "Meeting trusted people around shared activities requires discovery, identity, payment and safety tools in one experience.", solution: "A mobile social marketplace combines verified profiles, activity booking, payment flows, notifications and moderation.", businessValue: "Creates a scalable two-sided marketplace with trust mechanisms that support conversion and retention.", features: ["Identity verification", "Activity discovery and booking", "Payments and notifications", "Moderation workflows"], benefits: ["Improves marketplace trust", "Supports repeat engagement", "Simplifies organizer operations"], tradeoffs: ["Trust and safety operations add complexity", "Marketplace growth requires supply-demand balance"] },
  "Real-Time Chat": { audience: "Teams and communities needing reliable instant communication.", challenge: "Chat products must handle authentication, concurrent sessions and immediate message delivery without inconsistent state.", solution: "A MERN application uses Socket.io for bidirectional events, Redux for client state and JWT for protected sessions.", businessValue: "Provides a reusable communication foundation for support, community or collaboration products.", features: ["Real-time messaging", "Authenticated conversations", "Online presence", "Scalable client state"], benefits: ["Immediate user communication", "Reusable messaging architecture", "Responsive multi-session experience"], tradeoffs: ["WebSocket scaling needs shared infrastructure", "Delivery and read guarantees require careful design"] },
  "Rental & Travel": { audience: "Property owners and travelers managing short-term bookings.", challenge: "Booking systems must keep search, availability and owner inventory synchronized while preventing date conflicts.", solution: "A two-sided platform offers advanced discovery, owner and user dashboards, availability tracking and booking validation.", businessValue: "Turns inventory into bookable supply while reducing manual coordination and double-booking risk.", features: ["Advanced property filters", "Owner and traveler dashboards", "Availability calendar", "Date-conflict validation"], benefits: ["Improves booking conversion", "Gives owners inventory control", "Reduces scheduling errors"], tradeoffs: ["Availability must remain strongly consistent", "Payments and cancellation rules add domain complexity"] },
  "Geo Attendance": { audience: "Field teams and employers managing location-dependent attendance.", challenge: "Manual attendance is easy to misuse and gives managers limited confidence that check-ins happened at the workplace.", solution: "A mobile workflow uses GPS and geofencing to validate automatic check-in and check-out events with secure history.", businessValue: "Reduces attendance fraud and administrative effort while improving workforce visibility.", features: ["GPS geofencing", "Automatic attendance events", "Live location status", "Secure attendance history"], benefits: ["More reliable attendance records", "Less manual administration", "Useful field-work visibility"], tradeoffs: ["GPS accuracy varies by environment", "Location collection needs clear privacy controls"] },
  "EMA Alert System": { audience: "Traders monitoring price action around the 20-period exponential moving average.", challenge: "Continuous chart monitoring is time-consuming, and basic crossover alerts can generate noisy signals.", solution: "An automated watcher evaluates EMA 20 breakouts and applies signal rules before delivering timely alerts.", businessValue: "Reduces manual monitoring and helps users respond consistently to predefined market conditions.", features: ["EMA 20 monitoring", "Breakout detection", "Automated alerts", "False-signal filters"], benefits: ["Saves monitoring time", "Encourages rule-based decisions", "Delivers timely signals"], tradeoffs: ["Indicators cannot guarantee outcomes", "Market-data quality and latency affect signals"] },
  "Relic Atlas": { audience: "Archaeologists, detectorists and communities researching historical finds in Britain.", challenge: "Finds, geographic context and LiDAR evidence are often scattered across specialist sources.", solution: "A map-centered community platform brings discoveries, member tools and LiDAR-backed exploration into one research experience.", businessValue: "Creates a differentiated research community and makes specialist geographic data more accessible.", features: ["Interactive discovery maps", "Member dashboards", "Find documentation", "LiDAR-supported research"], benefits: ["Connects data with place", "Supports community knowledge", "Improves research discovery"], tradeoffs: ["Large map layers require optimization", "Sensitive site locations may require protection"] },
  "Pulpit Fill": { audience: "Churches seeking guest preachers and ministers looking for opportunities.", challenge: "Last-minute pulpit vacancies are commonly filled through fragmented personal networks and manual outreach.", solution: "A focused mobile marketplace connects verified churches and available preachers through searchable profiles and messaging.", businessValue: "Expands trusted supply, shortens placement time and gives a niche community a repeatable coordination channel.", features: ["Church and preacher profiles", "Availability discovery", "Direct communication", "iOS and Android access"], benefits: ["Faster vacancy fulfillment", "Broader trusted network", "Simpler coordination"], tradeoffs: ["Niche marketplaces depend on local density", "Verification is essential for trust"] },
  "Gyanoda": { audience: "Students preparing for competitive examinations across web and mobile.", challenge: "Past papers, practice material and progress tools are frequently fragmented or difficult to use on mobile devices.", solution: "A learning ecosystem organizes exam resources, structured practice and progress across accessible web and mobile products.", businessValue: "Improves learner retention and creates a scalable foundation for educational content and premium services.", features: ["Past-year question papers", "Structured exam practice", "Web and mobile access", "Student progress journey"], benefits: ["Centralizes study resources", "Supports consistent practice", "Extends access across devices"], tradeoffs: ["Content quality needs ongoing review", "Offline and low-bandwidth support affect reach"] },
  "Infinite Laundry": { audience: "Commercial customers comparing and booking professional laundry services.", challenge: "Service buyers need immediate clarity on capabilities, coverage and next steps before making an enquiry.", solution: "A premium responsive website structures services around a direct, low-friction booking and enquiry journey.", businessValue: "Improves qualified lead generation and presents the operation as a credible commercial partner.", features: ["Service-led navigation", "Responsive marketing pages", "Booking and enquiry journey", "Trust-focused presentation"], benefits: ["Clarifies the service offer", "Increases enquiry confidence", "Works across customer devices"], tradeoffs: ["Conversion depends on current service information", "Booking integrations require operational alignment"] },
  "Samprit Media": { audience: "Brands seeking creative, marketing and digital production services.", challenge: "Agency websites must communicate creative energy while making services and contact paths immediately understandable.", solution: "A high-impact studio storefront balances motion, brand expression, service proof and enquiry conversion.", businessValue: "Differentiates the agency and turns creative attention into qualified client conversations.", features: ["Bold agency presentation", "Service portfolio", "Motion-led interactions", "Conversion-focused contact path"], benefits: ["Strengthens brand recall", "Showcases capabilities quickly", "Supports lead generation"], tradeoffs: ["Heavy motion can affect performance", "Visual style must not reduce clarity"] },
  "SAP Freelance Hub": { audience: "Organizations needing specialist SAP integration and development support.", challenge: "Buyers need a clear view of technical SAP capability across integration, ABAP and manufacturing systems.", solution: "A focused enterprise services presence organizes SAP CPI, ABAP and MII expertise around practical engagement paths.", businessValue: "Builds technical credibility and helps enterprise prospects identify the right specialist service faster.", features: ["SAP service positioning", "CPI integration expertise", "ABAP development capability", "MII technical support"], benefits: ["Clarifies specialist expertise", "Supports enterprise enquiries", "Improves service discoverability"], tradeoffs: ["Enterprise claims require strong proof", "Long sales cycles need supporting content"] },
  "BillBnk": { audience: "Banking agents and customers needing assisted financial services.", challenge: "Agents often switch between fragmented tools for onboarding, payments, AEPS, wallet activity and payouts.", solution: "A mobile fintech product consolidates KYC, bill payment, wallet, AEPS and multi-bank payout workflows.", businessValue: "Enables agents to serve more customer needs from one product and creates multiple transaction revenue paths.", features: ["KYC onboarding", "AEPS transactions", "Bills and wallet operations", "Multi-bank payouts"], benefits: ["Consolidates agent workflows", "Expands service coverage", "Improves transaction visibility"], tradeoffs: ["Financial compliance is mandatory", "External banking dependencies affect availability"] },
  "EarnHub": { audience: "Clients hiring specialists and freelancers looking for relevant work.", challenge: "Broad freelance platforms can make discovery noisy and matching inefficient for both sides.", solution: "A focused marketplace structures profiles, requirements and matching to simplify professional discovery.", businessValue: "Creates a two-sided hiring channel that can monetize successful connections and premium visibility.", features: ["Professional profiles", "Project discovery", "Client-freelancer matching", "Marketplace workflows"], benefits: ["Reduces discovery effort", "Improves opportunity relevance", "Supports marketplace growth"], tradeoffs: ["Marketplace liquidity takes time", "Quality assurance requires moderation"] },
  "AI Code Editor": { audience: "Developers who want contextual AI help inside a browser-based workspace.", challenge: "Switching between an editor and generic AI chat loses code context and interrupts development flow.", solution: "A collaborative web editor connects live code context with explanation, generation and intelligent development assistance.", businessValue: "Shortens common development tasks and creates a platform for premium AI productivity workflows.", features: ["Contextual code assistance", "Code explanation and generation", "Real-time editor workflows", "Browser-based workspace"], benefits: ["Reduces context switching", "Accelerates routine coding", "Helps developers understand code"], tradeoffs: ["Generated code requires review", "Model usage introduces latency and cost"] },
  "AI Interview Platform": { audience: "Job candidates preparing for technical and behavioral interviews.", challenge: "Static question lists do not adapt to a candidate's resume, target role or previous performance.", solution: "An AI practice platform combines resume-aware retrieval, adaptive questioning and structured feedback with progress tracking.", businessValue: "Creates a repeatable personalized preparation experience suitable for subscriptions, institutions or placement programs.", features: ["Resume-aware RAG", "Adaptive interview questions", "Structured AI feedback", "Progress analytics"], benefits: ["Personalizes preparation", "Makes practice repeatable", "Highlights improvement areas"], tradeoffs: ["AI feedback is advisory, not definitive", "Resume data requires careful privacy handling"] },
};

export function getProjectInsight(project: ProjectLike): ProjectInsight {
  return insights[project.title] || {
    audience: `Organizations and users who need a dependable ${project.type.toLowerCase()}.`,
    challenge: `The target workflow was fragmented, time-consuming and difficult to manage consistently.`,
    solution: project.text,
    businessValue: `The product improves workflow clarity, user experience and the ability to scale delivery.`,
    features: project.tech.slice(0, 4).map(item => `${item}-powered capability`),
    benefits: ["Clearer user journey", "Reduced manual effort", "Scalable product foundation"],
    tradeoffs: ["Requires ongoing monitoring and maintenance", "External integrations can affect availability"],
  };
}
